server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AhnDaHoon/msa_spring_cloud_config
#          username:
#          password:
#        native:
#          search-locations: file:D:\msa-git-local-repo

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, busrefresh
